---
title: "Atividade 04"
subtitle: "ME613"
output: pdf_document
---



O comprimento da mão e altura foram medidos (em polegadas) para 167 universitários. Para importar os dados:

```{r}
dados <- read.table("handheight.txt", header = TRUE)
```

A) Apresente um gráfico de dispersão, incluindo a reta de regressão linear ajustada para a altura em função do comprimento da mão. Interprete os resultados.


B) Apresente as estimativas, respectivos erros-padrão, coeficiente de determinação e estimativa da variância do erro.


C) Apresente a tabela de análise de variância para a reta ajustada.


D) Apresente os valores para $SQReg$, $SQE$ e $SQT$.

E) Caso seja possível, apresente um teste de falta de ajuste utilizando a abordagem de comparar os modelos completo e reduzido. Apresente a tabela indicando a decomposição da $SQE$ em $SQFA$ e $SQEp$. Indique quais hipóteses estão sendo testadas, a estatística do teste e conclusão.

F) Apresente gráficos para diagnóstico do modelo. Comente cada um deles, especificando o objetivo de cada um no diagnóstico, e suas conclusões.

G) Apresente testes estatísticos apropriados para diagnóstico do modelo. Comente cada um deles, especificando as hipóteses e suas conclusões.


H) Depois de verificar as suposições do modelo através da análise dos resíduos, é possível testar a hipótese para checar se a relação linear entre `HandSpan` e `Height` é significativa? Em caso positivo, apresente o teste de hipótese em detalhes e o resultado obtido. Qual a conclusão?

I) Explique a relação do teste t para $\beta_1$ e o teste F que aparece nos resultados do comando `lm`.


J) Qual é a altura média de estudantes cuja largura do palmo é 17, 21 e 24 polegadas, respectivamente. Apresente também um intervalo de $95\%$ de confiança para estes casos.


K) Para um novo estudante, qual a estimativa de sua altura dado que sua largura do palmo é 17, 21 e 24 polegadas, respectivamente. Apresente também um intervalo de predição de $95\%$ para esses casos. Compare com os intervalos de confiança obtidos no item anterior. 

L) Apresente um gráfico de dispersão, juntamente com a reta ajustada e a banda de confiança para estimação da resposta média e o intervalo de predição para uma nova observação, ambos com nível de confiança de $95\%$.


M) Imagine que este modelo esteja sendo usado na UPA (Unicamp de Portas Abertas) para uma atividade com os alunos visitantes. Cada aluno visitante tem a largura do palmo da mão medido e os graduandos em estatística têm que advinhar a altura do aluno visitante. Indique a logística que você faria para advinhar a altura e como argumentaria com o aluno visitante sobre o resultado (correto ou não). Teria mais alguma coisa que poderia ser feita para melhorar a predição usando o mesmo conjunto de dados `handheight.txt`?